# TCL File Generated by Component Editor 15.1
# Thu Sep 03 22:34:41 MSK 2020
# DO NOT MODIFY


# 
# abus_avalon_sdram_bridge "abus_avalon_sdram_bridge" v1.0
# hitomi2500 2020.09.03.22:34:41
# Brigde to process avalon and abus requests to SDRAM
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module abus_avalon_sdram_bridge
# 
set_module_property DESCRIPTION "Brigde to process avalon and abus requests to SDRAM"
set_module_property NAME abus_avalon_sdram_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR hitomi2500
set_module_property DISPLAY_NAME abus_avalon_sdram_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL abus_avalon_sdram_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file abus_avalon_sdram_bridge.vhd VHDL PATH abus_avalon_sdram_bridge.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL abus_avalon_sdram_bridge
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file abus_avalon_sdram_bridge_tb.vhd VHDL PATH abus_avalon_sdram_bridge_tb.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point abus
# 
add_interface abus conduit end
set_interface_property abus associatedClock ""
set_interface_property abus associatedReset ""
set_interface_property abus ENABLED true
set_interface_property abus EXPORT_OF ""
set_interface_property abus PORT_NAME_MAP ""
set_interface_property abus CMSIS_SVD_VARIABLES ""
set_interface_property abus SVD_ADDRESS_GROUP ""

add_interface_port abus abus_address address Input 25
add_interface_port abus abus_read read Input 1
add_interface_port abus abus_data data Bidir 16
add_interface_port abus abus_chipselect chipselect Input 3
add_interface_port abus abus_direction direction Output 1
add_interface_port abus abus_interrupt_disable_out interrupt_disable_out Output 1
add_interface_port abus abus_interrupt interrupt Output 1
add_interface_port abus abus_write writebyteenable_n Input 2
add_interface_port abus saturn_reset reset Input 1


# 
# connection point avalon_sdram
# 
add_interface avalon_sdram avalon end
set_interface_property avalon_sdram addressUnits SYMBOLS
set_interface_property avalon_sdram associatedClock clock
set_interface_property avalon_sdram associatedReset reset
set_interface_property avalon_sdram bitsPerSymbol 8
set_interface_property avalon_sdram burstOnBurstBoundariesOnly false
set_interface_property avalon_sdram burstcountUnits SYMBOLS
set_interface_property avalon_sdram explicitAddressSpan 0
set_interface_property avalon_sdram holdTime 0
set_interface_property avalon_sdram isMemoryDevice true
set_interface_property avalon_sdram linewrapBursts false
set_interface_property avalon_sdram maximumPendingReadTransactions 1
set_interface_property avalon_sdram maximumPendingWriteTransactions 0
set_interface_property avalon_sdram readLatency 0
set_interface_property avalon_sdram readWaitStates 25
set_interface_property avalon_sdram readWaitTime 25
set_interface_property avalon_sdram setupTime 0
set_interface_property avalon_sdram timingUnits Cycles
set_interface_property avalon_sdram writeWaitTime 0
set_interface_property avalon_sdram ENABLED true
set_interface_property avalon_sdram EXPORT_OF ""
set_interface_property avalon_sdram PORT_NAME_MAP ""
set_interface_property avalon_sdram CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sdram SVD_ADDRESS_GROUP ""

add_interface_port avalon_sdram avalon_sdram_read read Input 1
add_interface_port avalon_sdram avalon_sdram_write write Input 1
add_interface_port avalon_sdram avalon_sdram_waitrequest waitrequest Output 1
add_interface_port avalon_sdram avalon_sdram_address address Input 26
add_interface_port avalon_sdram avalon_sdram_writedata writedata Input 16
add_interface_port avalon_sdram avalon_sdram_readdata readdata Output 16
add_interface_port avalon_sdram avalon_sdram_readdatavalid readdatavalid Output 1
add_interface_port avalon_sdram avalon_sdram_byteenable byteenable Input 2
set_interface_assignment avalon_sdram embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_sdram embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avalon_sdram embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_sdram embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_regs
# 
add_interface avalon_regs avalon end
set_interface_property avalon_regs addressUnits WORDS
set_interface_property avalon_regs associatedClock clock
set_interface_property avalon_regs associatedReset reset
set_interface_property avalon_regs bitsPerSymbol 8
set_interface_property avalon_regs burstOnBurstBoundariesOnly false
set_interface_property avalon_regs burstcountUnits WORDS
set_interface_property avalon_regs explicitAddressSpan 0
set_interface_property avalon_regs holdTime 0
set_interface_property avalon_regs linewrapBursts false
set_interface_property avalon_regs maximumPendingReadTransactions 1
set_interface_property avalon_regs maximumPendingWriteTransactions 0
set_interface_property avalon_regs readLatency 0
set_interface_property avalon_regs readWaitTime 1
set_interface_property avalon_regs setupTime 0
set_interface_property avalon_regs timingUnits Cycles
set_interface_property avalon_regs writeWaitTime 0
set_interface_property avalon_regs ENABLED true
set_interface_property avalon_regs EXPORT_OF ""
set_interface_property avalon_regs PORT_NAME_MAP ""
set_interface_property avalon_regs CMSIS_SVD_VARIABLES ""
set_interface_property avalon_regs SVD_ADDRESS_GROUP ""

add_interface_port avalon_regs avalon_regs_read read Input 1
add_interface_port avalon_regs avalon_regs_write write Input 1
add_interface_port avalon_regs avalon_regs_waitrequest waitrequest Output 1
add_interface_port avalon_regs avalon_regs_address address Input 8
add_interface_port avalon_regs avalon_regs_writedata writedata Input 16
add_interface_port avalon_regs avalon_regs_readdata readdata Output 16
add_interface_port avalon_regs avalon_regs_readdatavalid readdatavalid Output 1
set_interface_assignment avalon_regs embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_regs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_regs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_regs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point sdram
# 
add_interface sdram conduit end
set_interface_property sdram associatedClock clock
set_interface_property sdram associatedReset reset
set_interface_property sdram ENABLED true
set_interface_property sdram EXPORT_OF ""
set_interface_property sdram PORT_NAME_MAP ""
set_interface_property sdram CMSIS_SVD_VARIABLES ""
set_interface_property sdram SVD_ADDRESS_GROUP ""

add_interface_port sdram sdram_addr addr Output 13
add_interface_port sdram sdram_ba ba Output 2
add_interface_port sdram sdram_cas_n cas_n Output 1
add_interface_port sdram sdram_cke cke Output 1
add_interface_port sdram sdram_cs_n cs_n Output 1
add_interface_port sdram sdram_dq dq Bidir 16
add_interface_port sdram sdram_dqm dqm Output 2
add_interface_port sdram sdram_ras_n ras_n Output 1
add_interface_port sdram sdram_we_n we_n Output 1
add_interface_port sdram sdram_clk clk Output 1

