M48
; DRILL file {KiCad 7.0.7} date Mon Sep 18 11:20:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-18T11:20:04+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X3.4646Y-3.3661
X3.7787Y-3.3661
T2
X1.52Y-4.83
X4.0177Y-3.8031
T3
X3.1909Y-3.8031
X4.15Y-4.83
T0
M30
