M48
; DRILL file KiCad 10.0.0 date 2026-05-18T20:20:30
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-18T20:20:30+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
%
G90
G05
T1
X3.7024Y3.2339
X3.7024Y3.0063
T2
X2.4072Y3.4154
X2.7213Y3.4154
T3
X2.9603Y2.9784
T4
X2.1335Y2.9784
M30
